# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 22:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(upload_to='media/posters')),
                ('director', models.CharField(max_length=140)),
                ('created_date', models.DateField(default=datetime.datetime(2017, 9, 11, 22, 37, 8, 809724, tzinfo=utc))),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(max_length=140)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateField(default=datetime.datetime(2017, 9, 11, 22, 37, 8, 810831, tzinfo=utc))),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
