# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
