# Generated by Django 2.1.5 on 2019-02-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("movies", "0007_auto_20170922_2150")]

    operations = [
        migrations.AlterModelOptions(
            name="movie", options={"ordering": ["-created_by"]}
        )
    ]
